# Generated by Django 6.1.1 on 2026-10-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
